name: lint
on:
  push:
    paths:
      - '.github/workflows/lint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
  pull_request:
    paths:
      - '.github/workflows/lint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
