name: tests
on:
  push:
    paths-ignore:
    - '**/*.md'
    - '.github/workflows/lint.yml'
    - 'LICENSE'
  pull_request:
    paths-ignore:
    - '**/*.md'
    - '.github/workflows/lint.yml'
    - 'LICENSE'
jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test -c release
  linux:
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: swift:5.3
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test -c release --enable-test-discovery
