name: test
on: [push, pull_request]
jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run tests
      run: swift test
  linux:
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: swift:5.3
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run tests
      run: swift test --enable-test-discovery
