name: tests
on:
  push:
    paths-ignore:
    - '**/*.md'
    - '.github/workflows/lint.yml'
    - 'LICENSE'
  pull_request:
    paths-ignore:
    - '**/*.md'
    - '.github/workflows/lint.yml'
    - 'LICENSE'
jobs:
  macos:
    name: macOS
    runs-on: macos-11
    steps:
    - name: Select latest available Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run tests
      run: swift test --enable-code-coverage
    - name: Convert coverage to lcov
      run: xcrun llvm-cov export -format=lcov .build/debug/*PackageTests.xctest/Contents/MacOS/*PackageTests -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
    - name: Upload coverage
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
  linux:
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: swift:5.4
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run tests
      run: swift test
