name: tests
on:
  push:
    paths-ignore:
    - '**/*.md'
    - '.github/workflows/lint.yml'
    - 'LICENSE'
  pull_request:
    paths-ignore:
    - '**/*.md'
    - '.github/workflows/lint.yml'
    - 'LICENSE'
jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
    - uses: fwal/setup-swift@v1
      with:
        swift-version: '5.4'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run tests
      run: swift test --enable-code-coverage
    - name: Convert coverage to lcov
      run: xcrun llvm-cov export -format=lcov .build/debug/*PackageTests.xctest/Contents/MacOS/*PackageTests -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
  linux:
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: swift:5.4
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run tests
      run: swift test
