name: tests
on:
  push:
    paths-ignore:
    - '**/*.md'
    - '.github/workflows/lint.yml'
    - 'LICENSE'
  pull_request:
    paths-ignore:
    - '**/*.md'
    - '.github/workflows/lint.yml'
    - 'LICENSE'
jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test --enable-code-coverage
    - name: Prepare code coverage
      run: mkdir -p ./coverage && \
        xcrun llvm-cov export -format=lcov
              -instr-profile=.build/debug/codecov/default.profdata \
              .build/debug/*.xctest/Contents/MacOS/*PackageTests > ./coverage/info.lcov
    - name: Submit code coverage
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.COVERALLS_TOKEN }}
  linux:
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: swift:5.3
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test --enable-test-discovery
